### ISSUE TITLE
/api/session/{id} 보안 문제

### ISSUE THREAD

**Issue by woong-jae** [AL-GONG/Server#66]
내가 속한 스터디가 아니더라도 sessionId를 알고 있다면, 세션에 접근할 수 있는 문제점이 발생합니다. 세션 뿐만 아니라 id를 사용해서 정보를 가져오는 엔드 포인트 모두 공통적으로 발생할 수 있는 문제입니다.

**Comment by choco-one** [comment]
Study, Session, Problem, Solution, Review 각각 API를 실행할 때 StudyAuth 검사를 하여 스터디에 소속한 멤버인지 확인하도록 추가할 예정입니다

**Comment by choco-one** [comment]
@Auth 어노테이션을 추가해 팀장과 스터디에 속한 멤버만 접근할 수 있도록 수정했습니다.
